server:
  port: 2222

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/amazon
    username: root
    password: xjhxjh99
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/